# Generated by Django 3.1.3 on 2021-01-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210107_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='sick_approach_form',
            name='differential_diagnosis',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sick_approach_form',
            name='drug_choices',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='sick_approach_form',
            name='final_diagnosis',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='clinical_sign',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='sickness_history',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='start_dose_date',
            field=models.DateTimeField(),
        ),
    ]
