# Generated by Django 3.1.3 on 2021-01-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vet_Forms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_sick_approach_form', models.BooleanField(default=False)),
                ('is_dead_approach_form', models.BooleanField(default=False)),
                ('is_surgical_approach_form', models.BooleanField(default=False)),
                ('is_deworming_form', models.BooleanField(default=False)),
                ('is_vaccination_form', models.BooleanField(default=False)),
                ('is_artificial_insemination_form', models.BooleanField(default=False)),
                ('is_calf_registration_form', models.BooleanField(default=False)),
                ('is_livestock_inventory_form', models.BooleanField(default=False)),
                ('is_farm_consultation_form', models.BooleanField(default=False)),
                ('is_pregnancy_diagnosis_form', models.BooleanField(default=False)),
                ('species_affected', models.IntegerField(choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default=0)),
                ('num_of_species_affected', models.IntegerField()),
                ('report_created_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-report_created_on'],
            },
        ),
        migrations.CreateModel(
            name='Sick_Approach_Form',
            fields=[
                ('form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('disease_nature', models.IntegerField(choices=[('A', 'acute'), ('S', 'sub_acute')], default=0)),
                ('clinical_sign', models.CharField(default='', max_length=100)),
                ('disease_diagnosis', models.IntegerField(choices=[('C', 'clinical_signs'), ('L', 'laboratory')], default=0)),
                ('differential_diagnosis', models.CharField(default='', max_length=100)),
                ('final_diagnosis', models.CharField(default='', max_length=100)),
                ('sickness_duration', models.DurationField()),
                ('sickness_history', models.CharField(default='', max_length=100)),
                ('drug_choices', models.CharField(default='', max_length=100)),
                ('treatment_duration', models.DurationField()),
                ('start_dose_date', models.DateTimeField()),
                ('prognosis', models.IntegerField(choices=[('G', 'good'), ('F', 'fair'), ('P', 'poor')], default=0)),
                ('harmony_with_clinic_signs_and_lab', models.IntegerField(choices=[('Y', 'yes'), ('N', 'no')], default=0)),
                ('cause_of_death_if_in_no_harmony', models.CharField(blank=True, max_length=100, null=True)),
                ('disease_one_of_the_zoonotic', models.IntegerField(choices=[('Y', 'yes'), ('N', 'no')], default=0)),
                ('advice_given_if_zoonotic', models.CharField(blank=True, max_length=100, null=True)),
                ('relapse', models.IntegerField(choices=[('Y', 'yes'), ('N', 'no')], default=0)),
                ('cause_if_relapse', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
