# Generated by Django 3.1.3 on 2021-01-19 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sick_approach_form',
            old_name='form',
            new_name='vet_form',
        ),
    ]
