# Generated by Django 3.1.3 on 2021-01-18 08:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
        ('portals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vet_forms',
            name='farm_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.farm'),
        ),
    ]
