# Generated by Django 3.1.3 on 2021-01-21 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0004_surgical_approach_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artificial_Insemination_Form',
            fields=[
                ('vet_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('cow_code', models.CharField(max_length=20, unique=True)),
                ('age_of_animal', models.IntegerField(default=1)),
                ('time_of_heat_sign', models.DateTimeField()),
                ('date_of_insemination', models.DateTimeField()),
                ('nature_of_the_breeding', models.CharField(blank=True, max_length=100, null=True)),
                ('sire_name', models.CharField(max_length=200)),
                ('sire_origin', models.CharField(max_length=200)),
                ('bull_code', models.CharField(blank=True, max_length=100, null=True)),
                ('sex_of_the_calf_born', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=20)),
                ('date_of_birth', models.DateTimeField()),
                ('nature_of_birth', models.CharField(choices=[('A', 'Alive'), ('D', 'Dead')], default='A', max_length=20)),
                ('number_of_repeat', models.CharField(blank=True, max_length=100, null=True)),
                ('abortion_rate', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_for_the_cause_of_abortion', models.CharField(blank=True, max_length=100, null=True)),
                ('breed_used', models.CharField(blank=True, max_length=100, null=True)),
                ('source_of_semen', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_repeat_checked', models.DateTimeField()),
                ('date_of_pregnancy_diagnosis', models.DateTimeField()),
                ('expected_date_of_calving', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Calf_Registration_Form',
            fields=[
                ('vet_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('calf_code', models.CharField(max_length=20)),
                ('sex_of_the_calf', models.CharField(choices=[('M', 'male'), ('F', 'female')], default='M', max_length=20)),
                ('birth_weight', models.IntegerField()),
                ('breed_of_the_calf', models.CharField(max_length=20)),
                ('colour_of_the_breed', models.CharField(max_length=20)),
                ('status_of_the_calf', models.CharField(choices=[('H', 'Healthy'), ('D', 'Deformed')], default='H', max_length=100)),
                ('breeching_level_of_the_calf', models.CharField(choices=[('F', 'First'), ('S', 'Second'), ('T', 'Third'), ('P', 'Pedegree')], default='F', max_length=100)),
                ('sire_details', models.CharField(blank=True, max_length=100, null=True)),
                ('expected_date_of_weaning', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Deworming_Form',
            fields=[
                ('vet_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('species_targeted', models.CharField(choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20)),
                ('number_of_adults', models.IntegerField(default=1)),
                ('number_of_young_ones', models.IntegerField(default=1)),
                ('body_condition_of_the_animal', models.CharField(choices=[('G', 'good'), ('F', 'fair'), ('P', 'poor')], default='G', max_length=20)),
                ('date_of_deworming', models.DateTimeField()),
                ('drug_choices', models.CharField(default='', max_length=100)),
                ('target_parasites', models.CharField(blank=True, max_length=100, null=True)),
                ('withdrawal_period', models.DurationField()),
                ('side_effects', models.CharField(blank=True, max_length=100, null=True)),
                ('next_date_deworming', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Livestock_Inventory_Form',
            fields=[
                ('vet_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('species_targeted', models.CharField(choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20)),
                ('number_of_the_male_animals', models.IntegerField(default=1)),
                ('number_of_the_female_animals', models.IntegerField(default=1)),
                ('number_of_live_animals', models.IntegerField(default=1)),
                ('number_of_dead_animals', models.IntegerField(default=1)),
                ('specify_the_cause_of_the_dead', models.CharField(blank=True, max_length=100, null=True)),
                ('is_your_animals_insured', models.CharField(choices=[('Y', 'yes'), ('N', 'no')], default='Y', max_length=20)),
                ('if_yes_give_insuring_company', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_culling', models.DateTimeField()),
                ('give_reason_for_culling', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Pregnancy_Diagnosis_Form',
            fields=[
                ('vet_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('cow_code', models.CharField(max_length=20)),
                ('date_of_insemination', models.DateTimeField()),
                ('date_of_pregnancy_diagnosis', models.DateTimeField()),
                ('result_of_diagnosis', models.CharField(choices=[('P', 'positive'), ('N', 'Negative')], default='P', max_length=200)),
                ('if_result_is_negative_give_observation', models.CharField(blank=True, max_length=100, null=True)),
                ('next_date_of_pregnancy_diagnosis', models.DateTimeField()),
                ('expected_date_of_delivery', models.DateTimeField()),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaccination_Form',
            fields=[
                ('vet_form', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='portals.vet_forms')),
                ('species_targeted', models.CharField(choices=[('0', 'cattle'), ('1', 'sheep'), ('2', 'goat'), ('3', 'donkey'), ('4', 'dog'), ('5', 'horse'), ('6', 'poultry'), ('7', 'others')], default='0', max_length=20)),
                ('number_of_animals_vaccinated', models.IntegerField(default=1)),
                ('animal_breed', models.CharField(blank=True, max_length=100, null=True)),
                ('other_description', models.CharField(blank=True, max_length=100, null=True)),
                ('targetted_disease', models.CharField(max_length=20)),
                ('vaccines_used', models.CharField(blank=True, max_length=100, null=True)),
                ('date_of_vaccination', models.DateTimeField()),
                ('next_date_of_vaccination', models.DateTimeField()),
                ('name_of_the_crush', models.CharField(blank=True, max_length=100, null=True)),
                ('nature_of_the_vacination_program', models.CharField(choices=[('M', 'Mass_vaccination'), ('R', 'Ring_vaccination'), ('I', 'Individual')], default='M', max_length=200)),
                ('comment', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='vet_forms',
            options={'ordering': ['-report_created_on']},
        ),
        migrations.AlterField(
            model_name='sick_approach_form',
            name='prognosis',
            field=models.CharField(choices=[('G', 'good'), ('F', 'fair'), ('P', 'poor')], default='G', max_length=20),
        ),
    ]
